### ISSUE TITLE
Add more detail to docs

### ISSUE THREAD

**Issue by some1ataplace** [un33k/python-ipware#1]
It is not 100% clear how to use this with django or flask and it leaves a lot to interpretation. This may cause users like myself problems where I am guessing and not even sure if I am doing the right thing. 

For example, if migrating from django-ipware, how do you recreate IPWARE_META_PRECEDENCE_ORDER or IPWARE_PRIVATE_IP_PREFIX settings? Since django-ipware is planned to be deprecated, how do we properly migrate to python-ipware? Why use request.META instead of request.headers.items()? Explain how to use this library in either a WSGI versus ASGI environment and if there are any differences? 

These are just some questions I have. Adding more scenarios with coding examples to the documentation would be beneficial. It would also be helpful to build upon the "How to use" section.

**Comment by un33k** [comment]
This package provides sufficient details to be utilized by users of any Python framework. The IP header must be passed in, and details on how each package makes the IP header available can be found in the documentation of the respective framework.

This package is primarily used for security purposes, and users are expected to know how to read documentation and implement the necessary security measures.

Users are encouraged to simply input the parameters this module requires. How these parameters are acquired should remain within the scope of the framework being used.
