### ISSUE TITLE
check condition for proxy_count = 0 in is_proxy_count_valid with strict=True

### ISSUE THREAD

**Issue by FraKraBa** [un33k/python-ipware#18]
If I run
```
ipw = IpWare(precedence=('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', ), leftmost=True, proxy_count=0, proxy_list=[])
ipw.get_client_ip({'HTTP_X_FORWARDED_FOR': "177.139.233.139, 198.84.193.157, 198.84.193.158"}, strict=True)
```
I would expect that `strict=True` would be respected and the condition `self.proxy_count == ip_count - 1` would also be checked for `proxy_count = 0`.
However, I found that the call `proxy_count_validated = self.is_proxy_count_valid(ip_list, strict)` inside `get_client_ip` always returns `True` since `proxy_count < 1`.
I would suggest to introduce `proxy_count = None` in order to not check the `proxy_count` but check it for `proxy_count = 0` .

**Comment by un33k** [comment]
@FraKraBa  why don't you take this for a spin and see how it goes. 

https://github.com/un33k/python-ipware/pulls

Also, have a look at the changes as  well.

**Comment by FraKraBa** [comment]
Thanks a lot for the fast reply. Yes, it works for my usecase. However, I have 2 suggestions after looking at the changes. I've added them as comments to the pull request

**Comment by un33k** [comment]
Merged and closed.  Thx

**Comment by FraKraBa** [comment]
Thank you, this works for me. I still have one small suggestion: In `get_best_ip` in the part where the incoming ips match our proxy count, I think that the check for `self.proxy_count > 0` should be removed since the code now also checks for self.proxy_count = 0.

**Comment by un33k** [comment]
feel free to raise a pr
