### ISSUE TITLE
Add py.typed file for static type checking compatability

### ISSUE THREAD

**Issue by stumpylog** [un33k/python-ipware#2]
This package looks to be very nicely typed, but it is missing a `py.typed` file from PEP 561.

There's a quick example here for setup.py: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by un33k** [comment]
Sure thing? A PR would be appreciated.

**Comment by stumpylog** [comment]
Sure, i'll open one.  Any interest (as a separate PR) in combining the setup.cfg, setup.py all into pyproject?

**Comment by un33k** [comment]
Sure thing. If we move to newer way of doing things without losing functionalities.
