### ISSUE TITLE
Readme tip for handling X-Forwarded-For is incorrect for GCP's Google Loadbalancer

### ISSUE THREAD

**Issue by OscarVanL** [un33k/python-ipware#22]
The README says:

> The [de-facto standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) for identifying the originating client IP address is to use the leftmost IP in the X-Forwarded-For header, following the pattern client, proxy1, proxy2. Here, the rightmost IP is considered the most trusted proxy.

However, for anyone serving an application behind a Google loadbalancer will be vulnerable to IP spoofing if they follow these tips.

The header as provided by the Google Loadbalancer is documented [here](https://cloud.google.com/load-balancing/docs/https#x-forwarded-for_header). It says:

> If there is no X-Forwarded-For header on the incoming request, these two IP addresses are the entire header value:
> `X-Forwarded-For: <client-ip>,<load-balancer-ip>`
>
> If the request includes an X-Forwarded-For header, the load balancer preserves the supplied value _before_ the `<client-ip>,<load-balancer-ip>`:
> `X-Forwarded-For: <supplied-value>,<client-ip>,<load-balancer-ip>`

In this scenario, if we simply use the left-most value, then any user can spoof their IP address by simply setting the `X-Forwarded-For` header themselves.

In credit to the README, [this section](https://github.com/un33k/python-ipware?tab=readme-ov-file#trusted-proxies) does address this point, as I have a fixed proxy count so can solve it this way.

**Comment by un33k** [comment]
Please note that if there are reverse proxies between the real client and your LB and if no X-Forwarded-For is provided, the IP address of the reverse proxy serves as the client IP address within our control and consideration.

However, if the reverse proxy provides the X-Forwarded-For, they have supplied the `actual` client IP address, which works effectively when it is added in front of the LB X-Forwarded-For.

Also, we should note the [warning](https://github.com/un33k/python-ipware?tab=readme-ov-file#addressing-ip-address-spoofing) at the top of the readme file concerning spoofing. We rely solely on the information received from the remote server, so it is recommended to utilize X-Forwarded-For, Trusted Proxy IP / Count, and firewall regulations to establish a solution that aligns with your requirements.

It's great to hear that the proxy count is proving useful in your situation.

**Comment by OscarVanL** [comment]
Thanks, to be honest I think your README has enough warnings. These headers are just very fiddly and often non-standard.
